{% set version = "0.0.6" %}
{% set python_min = "3.10" %}

package:
  name: setuptools-generate
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/setuptools-generate/setuptools-generate-{{ version }}.tar.gz
  sha256: 6e23241d9ecfdfddf9e50a495f3092b60be3ca6f4a5e116c8c3e7f2b646ba725

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ={{ python_min }}
    - pip
    - setuptools-scm >=6.2
    - setuptools
  run:
    - python >={{ python_min }}
    - click
    - python-help2man
    - markdown-it-py
    - setuptools
    - shtab
    - tomli

test:
  commands:
    - pip check
  imports:
    - setuptools_generate
  requires:
    - pip
    - python ={{ python_min }}

about:
  home: https://github.com/Freed-Wu/setuptools-generate
  dev_url: https://github.com/Freed-Wu/setuptools-generate
  summary: Generate shell completions and man page when building a python package.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
